### ISSUE TITLE
License imbroglio: which one?

### ISSUE THREAD

**Issue by Guts** [opengisch/pgserviceparser#10]
Hi @3nids @signedav,

Could you clarify under which license is this project among:

- [GPL2+ in setup.py](https://github.com/opengisch/pgserviceparser/blob/4a304617a709a07c2e2490bfdce03defb37fb0d8/setup.py#L17)
- [MIT in setup.py](https://github.com/opengisch/pgserviceparser/blob/4a304617a709a07c2e2490bfdce03defb37fb0d8/setup.py#L19) too
- [GPL 3 in LICENSE](https://github.com/opengisch/pgserviceparser/blob/4a304617a709a07c2e2490bfdce03defb37fb0d8/LICENSE#L2)

**Comment by Guts** [comment]
MIT or Apache 2 sounds reasonable for this kind of project but it's just my 2 cents.

**Comment by 3nids** [comment]
let's go for MIT, this sounds reasonable as you say!
