### ISSUE TITLE
Windows fallback path

### ISSUE THREAD

**Issue by signedav** [opengisch/pgserviceparser#25]
Maybe it's possible to have a fallback for the windows case:
` %APPDATA%\postgresql\.pg_service.conf`

**Comment by gacarrillor** [comment]
I've fixed this in the plugin (see https://github.com/opengisch/qgis-pg-service-parser-plugin/pull/29), and would be happy to move it to the lib.

**Comment by signedav** [comment]
That would make sense, yes. Thanks a lot.

You can make releases with this plugin anytime as long as you know there are no regressions.
